# -*- coding: utf-8 -*-
"""dogs_vs_cats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x28JsWhhOUuUao_lUXna8ceIPqcTD8Zl
"""

from google.cloud import storage
import pandas as pd
import os

#Authentication using service account.

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] ="/content/dogs-vs-cats-354105-19b7b157b2b8.json"

BUCKET='dogs_cats_bucket1'
DELIMITER='/'
TRAIN_PREFIX='train/'

TRAIN_BASE_PATH = f'gs://{BUCKET}/{TRAIN_PREFIX}'

print("Starting the import file generation process")
print("Process Details")
print(f"BUCKET : {BUCKET}")

storage_client = storage.Client()


data = []

print("Fetchig list of Train objects")
train_blobs = storage_client.list_blobs(BUCKET, prefix=TRAIN_PREFIX, delimiter=DELIMITER)




for blob in train_blobs:
    label = "cat" if "cat" in blob.name else "dog"
    full_path = f"gs://{BUCKET}/{blob.name}"
    data.append({
        'GCS_FILE_PATH': full_path,
        'LABEL': label
    })


df = pd.DataFrame(data)

df.to_csv('train.csv', index=False, header=False)

